@startuml actividad
allowmixing


rectangle "Sprint Planning" as planning #Gray

'--------------- recursos --------------------------- 

rectangle "Backlog" as product_backlog1 #Green
rectangle "Sprint Backlog" as sprint_backlog1 #Green

rectangle "Pizarra" as blackboard1 #Green
rectangle "Video Conferencia" as video1 #Green
rectangle "Chat" as chat1 #Green

'--------------- perfiles ------------------

() "<&star>Ingeniero de Requerimientos" as rem1 #LightBlue
() "<&star>Team Member" as tm1 #LightBlue

'-------------- recursos salas -------------

() "<&star>Sala" as room1 #Orange


planning -[#Green]-> product_backlog1
planning -[#Green]-> sprint_backlog1
planning -u[#Green]-> chat1
planning -u[#Green]-> video1
planning -u[#Green]-> blackboard1

planning "1" -d[#Blue]-> "1" rem1
planning "1" -d[#Blue]-> "*" tm1

planning -d[#Orange]-> room1


'---------- awareness ------

object "<&star>Presencia" as Presencia1 {
    .
    <&cog>(Ingeniero de Requerimientos) Chat->entrar
    <&cog>(Team Member) Chat->entrar
    .
    <&cog>(Ingeniero de Requerimientos) Pizarra->entrar
    <&cog>(Team Member) Pizarra->entrar    
    .
    <&cog>(Ingeniero de Requerimientos) Video Conferencia->entrar
    <&cog>(Team Member) Video Conferencia->entrar    

}

Presencia1 --> video1
Presencia1 --> chat1
Presencia1 --> blackboard1


object "<&star>Presencia" as Presencia_room1 {
    .
    <&cog>(Ingeniero de Requerimientos) Sala->entrar
    <&cog>(Team Member) Sala->entrar
    .
    <&cog>(Ingeniero de Requerimientos) Sala->salir
    <&cog>(Team Member) Sala->salir
}

Presencia_room1 --u--> room1

object "<&star>Acción" as Acción1 {
    .
    <&cog>(Ingeniero de Requerimientos) Chat->escribir
    <&cog>(Team Member) Chat->escribir
    .
    <&cog>(Ingeniero de Requerimientos) Pizarra->dibujar
    <&cog>(Team Member) Pizarra->dibujar
    .
    <&cog>(Ingeniero de Requerimientos) Video Conferencia->hablar
    <&cog>(Team Member) Video Conferencia->hablar    
}

Acción1 --> chat1
Acción1 --> blackboard1
Acción1 --> video1


object "<&star>Cambios" as Cambios1 {
    .
    <&cog>(Ingeniero de Requerimientos) Backlog->escribir
    <&cog>(Team Member) Backlog->escribir
    .
    <&cog>(Ingeniero de Requerimientos) Sprint Backlog->escribir
    <&cog>(Team Member) Sprint Backlog->escribir
    .
    <&cog>(Ingeniero de Requerimientos) Archivos->subir
    <&cog>(Team Member) Archivos->subir    
    .
    <&cog>(Team Member) Editor de Código->escribir
    <&cog>(Team Member) Versionado->commit
}

Cambios1 -d-> product_backlog1
Cambios1 -d-> sprint_backlog1

















'-----------------------------------------------------------

rectangle "Sprint" as sprint #Gray
note bottom: Genera un entregable en\nServidor de integración continua\nque usan las actividades siguientes

'--------------- recursos --------------------------- 

rectangle "Sprint Backlog" as sprint_backlog2 #Green
rectangle "Pizarra" as blackboard2 #Green
rectangle "Archivos" as files2 #Green
rectangle "Editor de Código" as editor2 #Green
rectangle "Versionado" as git2 #Green
rectangle "Servidor de Integración Continua" as ci2 #Green
rectangle "Editor de Gráficos" as g_editor2 #Green
note top: "si no es herramineta colaborativa no va no?" 

rectangle "Video Conferencia" as video2 #Green
rectangle "Chat" as chat2 #Green

'--------------- perfiles ------------------

() "<&star>Team Member" as tm2 #LightBlue

'-------------- recursos salas -------------

() "<&star>Sala" as room2 #Orange

sprint "1" -d[#Blue]-> "*" tm2

sprint -d[#Orange]-> room2

sprint -u[#Green]-> chat2
sprint -u[#Green]-> video2

sprint -[#Green]-> sprint_backlog2
sprint -u[#Green]-> blackboard2
sprint -u[#Green]-> files2
sprint -u[#Green]-> editor2
sprint -u[#Green]-> git2
sprint -u[#Green]-> g_editor2
sprint -[#Green]-> ci2


'---------- awareness ------

object "<&star>Presencia" as Presencia2 {
    .
    <&cog>(Team Member) Chat->entrar
    <&cog>(Team Member) Pizarra->entrar    
    <&cog>(Team Member) Video Conferencia->entrar    
    <&cog>(Team Member) Editor de Código->entrar
}

Presencia2 --> video2
Presencia2 --> chat2
Presencia2 --> blackboard2
Presencia2 --> editor2

object "<&star>Presencia" as Presencia_room2 {
    .
    <&cog>(Team Member) Sala->entrar
    <&cog>(Team Member) Sala->salir
}

Presencia_room2 --u--> room2

object "<&star>Acción" as Acción2 {
    .
    <&cog>(Team Member) Chat->escribir
    <&cog>(Team Member) Pizarra->dibujar
    <&cog>(Team Member) Video Conferencia->hablar    
}

Acción2 --> chat2
Acción2 --> blackboard2
Acción2 --> video2


object "<&star>Cambios" as Cambios2 {
    .
    <&cog>(Team Member) Servidor de Integración Continua->subir
    <&cog>(Team Member) Sprint Backlog->escribir
    <&cog>(Team Member) Archivos->subir    
    <&cog>(Team Member) Editor de Código->escribir
    <&cog>(Team Member) Versionado->push
}

Cambios2 --> sprint_backlog2
Cambios2 --> git2
Cambios2 --> files2
Cambios2 --> ci2














'----------------------------------------------------------------


rectangle "Daily Review\n15 min max" as daily #Gray
note left: "Los miembros cuentan un poco el progreso\nla pizarra solo para explicar rápido"
'------------- recursos ---------------------

rectangle "Sprint Backlog" as sprint_backlog3 #Green
rectangle "Video Conferencia" as video3 #Green
rectangle "Chat" as chat3 #Green
rectangle "Pizarra" as blackboard3 #Green

'--------------- perfiles ------------------

() "<&star>Team Member" as tm3 #LightBlue

'-------------- recursos salas -------------

() "<&star>Sala" as room3 #Orange


daily "1" -d[#Blue]-> "*" tm3
daily -d[#Orange]-> room3

daily -u[#Green]-> sprint_backlog3
daily -u[#Green]-> chat3
daily -u[#Green]-> video3
daily -u[#Green]-> blackboard3


'---------- awareness ------

object "<&star>Presencia" as Presencia3 {
    .
    <&cog>(Team Member) Chat->entrar
    <&cog>(Team Member) Pizarra->entrar    
    <&cog>(Team Member) Video Conferencia->entrar    
    <&cog>(Team Member) Editor de Código->entrar
}

Presencia3 --> video3
Presencia3 --> chat3
Presencia3 --> blackboard3


object "<&star>Presencia" as Presencia_room3 {
    .
    <&cog>(Team Member) Sala->entrar
    <&cog>(Team Member) Sala->salir
}

Presencia_room3 --u--> room3

object "<&star>Acción" as Acción3 {
    .
    <&cog>(Team Member) Chat->escribir
    <&cog>(Team Member) Pizarra->dibujar
    <&cog>(Team Member) Video Conferencia->hablar    
}

Acción3 --> chat3
Acción3 --> video3
Acción3 --> blackboard3


object "<&star>Cambios" as Cambios3 {
    .
    <&cog>(Team Member) Sprint Backlog->escribir
}

Cambios3 --> sprint_backlog3


object "<&star>Cambios" as Cambios_activity3 {
    .
    <&cog>(System) Daily Review->time_expired
    <&cog>(Team Member) Daily Review->speaker_selected
}
note bottom: Muestra cuando el reloj expira\ny cuando se selecciona a otro miembro para hablar

Cambios_activity3 -l-> daily









'--------------------------------------------------------------


rectangle "Sprint Review" as sprint_review #Gray
note bottom: Se analiza el entregable del sprint\ny se retroalimenta el sprint backlog\nse determina si se debe seguir con\nla demás funcionalidad

'------------- recursos ---------------------

rectangle "Sprint Backlog" as sprint_backlog4 #Green
rectangle "Video Conferencia" as video4 #Green
rectangle "Chat" as chat4 #Green
rectangle "Pizarra" as blackboard4 #Green
rectangle "Servidor de Integración Continua" as ci4 #Green

'--------------- perfiles ------------------

() "<&star>Team Member" as tm4 #LightBlue
() "<&star>Product Owner" as po4 #LightBlue
() "<&star>Stake Holder" as sh4 #LightBlue

'-------------- recursos salas -------------

() "<&star>Sala" as room4 #Orange


sprint_review "1" -d[#Blue]-> "*" tm4
sprint_review "1" -d[#Blue]-> "1" sh4
sprint_review "1" -d[#Blue]-> "1" po4
sprint_review -d[#Orange]-> room4

sprint_review -[#Green]-> sprint_backlog4
sprint_review -u[#Green]-> ci4
sprint_review -u[#Green]-> chat4
sprint_review -u[#Green]-> video4
sprint_review -u[#Green]-> blackboard4

'---------- awareness ------

object "<&star>Presencia" as Presencia4 {
    .
    <&cog>(Team Member) Chat->entrar
    <&cog>(Team Member) Video Conferencia->entrar    
    .
    <&cog>(Product Owner) Chat->entrar
    <&cog>(Product Owner) Video Conferencia->entrar    
    .
    <&cog>(Stake Holder) Chat->entrar
    <&cog>(Stake Holder) Video Conferencia->entrar        
}

Presencia4 --> video4
Presencia4 --> chat4

object "<&star>Presencia" as Presencia_room4 {
    .
    <&cog>(Team Member) Sala->entrar
    <&cog>(Team Member) Sala->salir
    .
    <&cog>(Product Owner) Sala->entrar
    <&cog>(Product Owner) Sala->salir
    .
    <&cog>(Stake Holder) Sala->entrar
    <&cog>(Stake Holder) Sala->salir
}

Presencia_room4 --u--> room4

object "<&star>Acción" as Acción4 {
    .
    <&cog>(Team Member) Chat->escribir
    <&cog>(Team Member) Video Conferencia->hablar
    <&cog>(Team Member) Sprint Backlog->escribir    
    .
    <&cog>(Product Owner) Chat->escribir
    <&cog>(Product Owner) Video Conferencia->hablar
    .
    <&cog>(Stake Holder) Chat->escribir
    <&cog>(Stake Holder) Video Conferencia->hablar

}

Acción4 --> chat4
Acción4 --> video4
Acción4 --> sprint_backlog4


object "<&star>Cambios" as Cambios4 {
    .
    <&cog>(Team Member) Servidor de Integración Continua->subir
    <&cog>(Team Member) Sprint Backlog->escribir
    <&cog>(Team Member) Archivos->subir    
    <&cog>(Team Member) Editor de Código->escribir
    <&cog>(Team Member) Versionado->push
}

Cambios4 --> sprint_backlog4
















'-------------------------------------------

rectangle "Sprint Retrospective" as sprint_retrospective #Gray


'-------------- recursos -------------------

rectangle "Sprint Backlog" as sprint_backlog5 #Green

rectangle "Video Conferencia" as video5 #Green
rectangle "Chat" as chat5 #Green

'--------------- perfiles ------------------

() "<&star>Team Member" as tm5 #LightBlue

'-------------- recursos salas -------------

() "<&star>Sala" as room5 #Orange



sprint_retrospective "1" -d[#Blue]-> "*" tm5
sprint_retrospective -d[#Orange]-> room5

sprint_retrospective -[#Green]-> sprint_backlog5
sprint_retrospective -u[#Green]-> chat5
sprint_retrospective -u[#Green]-> video5



'---------- awareness ------

object "<&star>Presencia" as Presencia5 {
    .
    <&cog>(Team Member) Chat->entrar
    <&cog>(Team Member) Video Conferencia->entrar    
}

Presencia5 --> video5
Presencia5 --> chat5

object "<&star>Presencia" as Presencia_room5 {
    .
    <&cog>(Team Member) Sala->entrar
    <&cog>(Team Member) Sala->salir
}

Presencia_room5 --u--> room5

object "<&star>Acción" as Acción5 {
    .
    <&cog>(Team Member) Chat->escribir
    <&cog>(Team Member) Video Conferencia->hablar
    <&cog>(Team Member) Sprint Backlog->escribir    
}

Acción5 --> chat5
Acción5 --> video5
Acción5 --> sprint_backlog5


object "<&star>Cambios" as Cambios5 {
    .
    <&cog>(Team Member) Sprint Backlog->escribir
}

Cambios5 --> sprint_backlog5




@enduml

















@startuml proceso
title "Proceso de Sprint"

state "Sprint Planning" as planning
state "Sprint" as sprint
state "Daily Review" as daily
state "Sprint Review" as review
state "Sprint Retrospective" as retrospective

'state f <<fork>>
state c <<choice>>

sprint -> daily : (Team Member) Daily Review->init
daily -> sprint : (Team Member) Daily Review->finish

[*] --> planning : (Team Member) Product Backlog->seleccionar
planning --> sprint : (Team Member) Sprint Backlog->seleccionar
sprint --> review : (Team Member) Sprint Backlog->finalizar
review --> c : (Team Member) Sprint Backlog->reviewed
c --> retrospective : existe mas funcionalidad
c --> [*] : no existe mas funcionalidad
retrospective --u--> planning : (Team Member) Sprint Retrospective->finish


@enduml



@startuml spint_protocol

state "Selección de Funcionalidad" as a1
a1: Available Operations:
a1: ==================================================
a1: (Team Member) Video->hablar
a1: (Team Member) Backlog->leer
a1: (Team Member) Sprint Backlog->leer
a1: (Team Member) Sprint Backlog->escribir
a1:
a1: Transition Operations :
a1: ==================================================
a1: (Team Member) Sprint Backlog->iniciar



state "Daily" as a2
a3: Available Operations:
a3: ==================================================
a3: (Team Member) Editor de Código->escribir
a3: (Team Member) Editor de Gráficos->editar
a3: (Team Member) Versionado->commit
a3: (Team Member) Versionado->pull
a3: (Team Member) Versionado->push
a3: (Team Member) Video->hablar
a3: (Team Member) Chat->escribir
a3: (Team Member) Chat->leer
a3: (Team Member) Archivos->descargar
a3: (Team Member) Archivos->subir
a3: (Team Member) Pizarra->dibujar
a3: (Team Member) Sprint Backlog->leer
a3: (Team Member) Sprint Backlog->escribir
a3:
a3: Transition Operations :
a3: ==================================================
a3: (Team Member) Sprint Backlog->finalizar



state "Trabajo Diario" as a3
a3: Available Operations:
a3: ==================================================
a3: (Team Member) Editor de Código->escribir
a3: (Team Member) Editor de Gráficos->editar
a3: (Team Member) Versionado->commit
a3: (Team Member) Versionado->pull
a3: (Team Member) Versionado->push
a3: (Team Member) Video->hablar
a3: (Team Member) Chat->escribir
a3: (Team Member) Chat->leer
a3: (Team Member) Archivos->descargar
a3: (Team Member) Archivos->subir
a3: (Team Member) Pizarra->dibujar
a3: (Team Member) Sprint Backlog->leer
a3: (Team Member) Sprint Backlog->escribir
a3:
a3: Transition Operations :
a3: ==================================================
a3: (Team Member) Sprint Backlog->finalizar



[*] --> a1
a1 --> a2
a2 --> [*]



@enduml